In [1]:
%cd ../..

/home/work/AnacondaProjects/combinators


In [2]:
import logging

import numpy as np
import probtorch
import torch

from examples.fep_control import fep_control
from combinators.model import active
from combinators.model import compose, foldable
from combinators.inference import importance
from combinators import utils

In [3]:
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

In [4]:
target = fep_control.MountainCarStep(state_dim=2, action_dim=1, observation_dim=2, batch_shape=(1,), discrete_actions=False, trainable=False)
proposal = fep_control.RecognitionStep(state_dim=2, observation_dim=2, batch_shape=(1,), discrete_actions=False, name='MountainCarStep', trainable=True)
agent = importance.propose(target, proposal)

In [5]:
agent = torch.load('examples/fep_control/fep_mountain_car_agent.dat')

In [6]:
theta, graph, log_weight = active.active_inference_test(agent, 'MountainCarContinuous-v0', online_inference=False, iterations=1000)

In [7]:
theta

(tensor([[0.2541, 0.4428]], grad_fn=<AddBackward0>),
 tensor([[29.1282]], grad_fn=<ExpandBackward>))

In [8]:
log_weight

tensor([-805.7183], grad_fn=<AddBackward0>)