In [1]:
%cd ../..

/home/eli/AnacondaProjects/combinators


In [2]:
import logging

import numpy as np
import probtorch
import torch

from combinators.inference import importance, mcmc
from combinators.kernel import kernel, mh
from combinators import utils

In [3]:
import examples.ais.ais_1d_gaussians as ais_example

In [4]:
logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

In [5]:
target = ais_example.AnnealingTarget(annealing_steps=20, batch_shape=(10,))

In [6]:
ais = mcmc.Move(target, mh.MHMoveKernel(target, kernel.GaussianKernel('AnnealingTarget', 'X_0'), moves=75), moves=20, count_target=True)

In [ ]:
annealed_points, trace, log_weight = ais()

> /home/eli/AnacondaProjects/combinators/combinators/kernel/mh.py(87)forward()
-> zs = zsp
tensor([-1.0098, -3.8142, -0.9010, -2.9797, -1.2074,  1.6452, -2.1624, -4.9441,
        -1.4903, -1.6014])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor(-2.0110)
> /home/eli/anaconda3/envs/funcytorch/lib/python3.6/site-packages/torch/nn/modules/module.py(477)__call__()
-> result = self.forward(*input, **kwargs)
> /home/eli/AnacondaProjects/combinators/combinators/inference/mcmc.py(31)forward()
-> xiq, log_weight_q = self.kernel(zs, xi, log_weight, *args, **kwargs)
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [ ]:
import matplotlib.pyplot as plt
from torch.distributions import Normal

In [ ]:
sample = torch.linspace(-10, 10, 100)
sample_probs = Normal(loc=torch.ones(1) * 3, scale=torch.ones(1) / 4).log_prob(sample).exp()

In [ ]:
plt.scatter(annealed_points.detach().numpy(), log_weight.exp())
plt.plot(sample.detach().numpy(), sample_probs.detach().numpy())

In [ ]:
annealed_points

In [ ]:
log_weight